import { FullApplicationForm } from './types';

export const INITIAL_FORM_STATE: FullApplicationForm = {
  positionApplied: {
    position: '',
    preferredLocation: '',
    startDate: '',
    noticePeriod: '',
    employmentType: '',
    trafficSource: '',
    workedHereBefore: '',
    workedHereBeforeDetails: '',
  },
  personalDetails: {
    title: '',
    titleOther: '',
    fullName: '',
    previousNames: '',
    dob: '',
    niNumber: '',
    homeAddress: '',
    mobileNumber: '',
    emailAddress: '',
    preferredContact: '',
  },
  nextOfKin: {
    name: '',
    relationship: '',
    phoneNumber: '',
    emailAddress: '',
  },
  bankDetails: {
    bankName: '',
    holderName: '',
    sortCode: '',
    accountNumber: '',
  },
  rightToWork: {
    legallyEntitled: '',
    evidenceProvided: '',
    shareCodeRef: '',
    visaExpiry: '',
    restrictions: '',
    restrictionDetails: '',
    sponsorshipRequired: '',
    officeCopiedChecked: '',
    officeCheckedBy: '',
    officeCheckedDate: '',
  },
  driveTravel: {
    holdLicence: '',
    licenceNo: '',
    accessToVehicle: '',
    businessInsurance: '',
    drivingEndorsements: '',
    endorsementDetails: '',
    maxHoursPerWeek: '',
    preferredShifts: [],
  },
  availability: {
    Monday: { am: false, pm: false, night: false },
    Tuesday: { am: false, pm: false, night: false },
    Wednesday: { am: false, pm: false, night: false },
    Thursday: { am: false, pm: false, night: false },
    Friday: { am: false, pm: false, night: false },
    Saturday: { am: false, pm: false, night: false },
    Sunday: { am: false, pm: false, night: false },
  },
  education: [
    { id: 'edu-1', school: '', qualification: '', grade: '', dateCompleted: '' }
  ],
  relevantTraining: {
    careCertificateInduction: { completed: '', provider: '', expiryDate: '' },
    safeguardingAdults: { completed: '', provider: '', expiryDate: '' },
    movingHandling: { completed: '', provider: '', expiryDate: '' },
    medicationAdministration: { completed: '', provider: '', expiryDate: '' },
    mentalHealthPBS: { completed: '', provider: '', expiryDate: '' },
    otherSpecialist: { completed: '', provider: '', expiryDate: '' },
  },
  employmentHistory: [
    {
      id: 'emp-1',
      employerNameAddress: '',
      jobTitle: '',
      startDateEndDate: '',
      mainDuties: '',
      reasonForLeaving: '',
      managerContactName: '',
      employerContactDetails: '',
    },
    {
      id: 'emp-2',
      employerNameAddress: '',
      jobTitle: '',
      startDateEndDate: '',
      mainDuties: '',
      reasonForLeaving: '',
      managerContactName: '',
      employerContactDetails: '',
    }
  ],
  employmentGaps: '',
  careSkills: {
    personalCare: '',
    medicationSupport: '',
    movingHandling: '',
    dementiaCare: '',
    learningDisabilityAutism: '',
    mentalHealthBehaviours: '',
    supportedLivingDomiciliary: '',
    careSummary: '',
  },
  referee1: {
    name: '',
    jobTitleRelationship: '',
    organisation: '',
    address: '',
    telephone: '',
    email: '',
    mayContact: '',
  },
  referee2: {
    name: '',
    jobTitleRelationship: '',
    organisation: '',
    address: '',
    telephone: '',
    email: '',
    mayContact: '',
  },
  dbsSafety: {
    hasDbs: '',
    dbsNo: '',
    registeredUpdateService: '',
    updateServiceChecked: '',
    everBarred: '',
    barDetails: '',
    hasConvictions: '',
    convictionDetails: '',
    subjectToDisciplinary: '',
    disciplinaryDetails: '',
    applicantAcknowledged: false,
  },
  healthAdjustments: {
    requireAdjustments: '',
    adjustmentDetails: '',
    healthConditions: '',
    healthDetails: '',
    otherSupportNeeds: '',
    otherNeedsDetails: '',
  },
  checklist: {
    proofOfIdentity: { received: '', verifiedBy: '', date: '' },
    rightToWorkEvidence: { received: '', verifiedBy: '', date: '' },
    proofOfAddress: { received: '', verifiedBy: '', date: '' },
    niEvidence: { received: '', verifiedBy: '', date: '' },
    dbsCertificate: { received: '', verifiedBy: '', date: '' },
    trainingCertificates: { received: '', verifiedBy: '', date: '' },
    bankDetailsChecked: { received: '', verifiedBy: '', date: '' },
  },
  declaration: {
    signature: '',
    date: '',
    printName: '',
  },
  officeUse: {
    receivedDate: '',
    shortlisted: '',
    interviewDateTime: '',
    interviewedBy: '',
    outcome: '',
    conditionalOfferSent: '',
    conditionalOfferDate: '',
    referencesStatus: '',
    rtwCompleted: '',
    dbsChecked: '',
    dbsCheckedDate: '',
    inductionBookedCompleted: '',
    startDateAgreed: '',
    recruitingManagerSignature: '',
    recruitingManagerName: '',
    recruitingManagerDate: '',
    decisionNotes: '',
  },
};

export const POSITIONS = [
  'Care Assistant',
  'Support Worker',
  'Senior Support Worker',
  'Care Manager',
  'Registered Nurse',
  'Domestic Assistant',
  'Administrator',
  'Other Care Professional',
];

export const LOCATIONS = [
  'Nelson (Head Office)',
  'Burnley & Pendle Area',
  'Blackburn & Darwen Area',
  'Accrington & Hyndburn Area',
  'Supported Living Residences',
  'Daffodils Domiciliary Services',
];

export const SHIFTS = [
  { id: 'Days', label: 'Days' },
  { id: 'Evenings', label: 'Evenings' },
  { id: 'Waking Nights', label: 'Waking Nights' },
  { id: 'Sleep ins', label: 'Sleep ins' },
  { id: 'Weekends', label: 'Weekends' },
  { id: 'Bank Holidays', label: 'Bank Holidays' },
];

export const EVIDENCE_TYPES = [
  'UK/Irish Passport',
  'Birth Certificate + NI Evidence',
  'Share Code (EU Settlement Scheme / Visa)',
  'Visa / BRP / eVisa',
  'Other official document',
];

// Rich, high-fidelity sample application dataset
export const SAMPLE_FORM_DATA: FullApplicationForm = {
  positionApplied: {
    position: 'Senior Support Worker',
    preferredLocation: 'Nelson (Head Office)',
    startDate: '2026-07-01',
    noticePeriod: '4 Weeks',
    employmentType: 'Full-time',
    trafficSource: 'Indeed search listing',
    workedHereBefore: 'No',
    workedHereBeforeDetails: '',
  },
  personalDetails: {
    title: 'Mrs',
    titleOther: '',
    fullName: 'Sarah Elizabeth Jenkins',
    previousNames: 'Sarah Elizabeth Cooper',
    dob: '1990-04-12',
    niNumber: 'QQ123456C',
    homeAddress: '24 Kingsland Street,\nBurnley, Lancashire,\nBB11 3AB',
    mobileNumber: '07712 345678',
    emailAddress: 'sarah.jenkins.care@example.com',
    preferredContact: 'Phone',
  },
  nextOfKin: {
    name: 'David Jenkins',
    relationship: 'Spouse',
    phoneNumber: '07722 987654',
    emailAddress: 'djenkins@example.com',
  },
  bankDetails: {
    bankName: 'HSBC UK Nelson',
    holderName: 'SARAH JENKINS',
    sortCode: '40-12-34',
    accountNumber: '87654321',
  },
  rightToWork: {
    legallyEntitled: 'Yes',
    evidenceProvided: 'UK/Irish Passport',
    shareCodeRef: 'RTW-987-928-UK',
    visaExpiry: '',
    restrictions: 'No',
    restrictionDetails: '',
    sponsorshipRequired: 'No',
    officeCopiedChecked: 'Yes',
    officeCheckedBy: 'H. Rostron',
    officeCheckedDate: '2026-06-16',
  },
  driveTravel: {
    holdLicence: 'Yes',
    licenceNo: 'JENKI904120SE99L',
    accessToVehicle: 'Yes',
    businessInsurance: 'Yes',
    drivingEndorsements: 'No',
    endorsementDetails: '',
    maxHoursPerWeek: '40',
    preferredShifts: ['Days', 'Evenings', 'Weekends'],
  },
  availability: {
    Monday: { am: true, pm: true, night: false },
    Tuesday: { am: true, pm: true, night: false },
    Wednesday: { am: true, pm: true, night: false },
    Thursday: { am: true, pm: true, night: false },
    Friday: { am: true, pm: true, night: false },
    Saturday: { am: true, pm: false, night: false },
    Sunday: { am: false, pm: true, night: false },
  },
  education: [
    { id: 'edu-1', school: 'Nelson & Colne College', qualification: 'NVQ Level 3 Health and Social Care', grade: 'Distinction', dateCompleted: 'July 2012' },
    { id: 'edu-2', school: 'Burnley High School', qualification: '8 GCSEs (Inc. Maths & English)', grade: 'Grades A*-C', dateCompleted: 'June 2008' }
  ],
  relevantTraining: {
    careCertificateInduction: { completed: 'Yes', provider: 'Hills Care Academy (No. HC-209-A)', expiryDate: 'None' },
    safeguardingAdults: { completed: 'Yes', provider: 'Pendle Council Safeguarding Board', expiryDate: '2027-10-15' },
    movingHandling: { completed: 'Yes', provider: 'Daffodils Care Internal Training', expiryDate: '2026-12-10' },
    medicationAdministration: { completed: 'Yes', provider: 'NHS Clinical Skills Hub', expiryDate: '2027-04-12' },
    mentalHealthPBS: { completed: 'Yes', provider: 'MENCAP Specialist Support Services', expiryDate: 'None' },
    otherSpecialist: { completed: 'Yes', provider: 'Dementia UK Core Modules', expiryDate: '2028-02-18' },
  },
  employmentHistory: [
    {
      id: 'emp-1',
      employerNameAddress: 'St Andrews Care Home,\n12 St Andrews Road, Nelson, BB9 8TT',
      jobTitle: 'Senior Support Worker',
      startDateEndDate: 'Aug 2018 - Present',
      mainDuties: 'Supervising a team of 4 healthcare assistants, drafting personalized task care sheets, managing medication MAR boards, and coordinating activity circles for residents with complex physical conditions.',
      reasonForLeaving: 'Looking to transition to domiciliary care with Daffodils to support patients directly in community residences.',
      managerContactName: 'Jeanette O\'Hara (Registered Manager)',
      employerContactDetails: 'j.ohara@standrewscare.co.uk / 01282 654321',
    },
    {
      id: 'emp-2',
      employerNameAddress: 'Lancashire Homecare Group,\nUniversity Way, Preston, PR1 2HE',
      jobTitle: 'DCS Care Assistant',
      startDateEndDate: 'Sep 2012 - Jul 2018',
      mainDuties: 'Providing daily personal hygiene routine support, medication prompts, preparing meals, and organizing light physical exercises for up to 10 elderly residents living alone.',
      reasonForLeaving: 'Acquired NVQ Level 3 and accepted a higher responsibility supervisor role.',
      managerContactName: 'Robert Vance (HR Manager)',
      employerContactDetails: 'hr@lancashirehomecare.co.uk',
    }
  ],
  employmentGaps: 'None. Continuous employment since graduation from NVQ Level 3 certification.',
  careSkills: {
    personalCare: 'Yes',
    medicationSupport: 'Yes',
    movingHandling: 'Yes',
    dementiaCare: 'Yes',
    learningDisabilityAutism: 'Yes',
    mentalHealthBehaviours: 'Yes',
    supportedLivingDomiciliary: 'Yes',
    careSummary: 'I have dedicated my entire 14-year professional life to patient dignity, compassion-first elderly care, and supporting residents with severe learning disabilities. I cherish the opportunity to build strong, friendly relationships with long-term care patients. This enables them to sustain their independence at home. I am highly proficient with hoisting safety procedures, diabetes insulin administration checks, and managing MAR registers.',
  },
  referee1: {
    name: 'Jeanette O\'Hara',
    jobTitleRelationship: 'Registered Care Home Manager (Current Supervisor)',
    organisation: 'St Andrews Care Home',
    address: '12 St Andrews Road, Nelson, BB9 8TT',
    telephone: '01282 654321',
    email: 'j.ohara@standrewscare.co.uk',
    mayContact: 'Only after conditional offer',
  },
  referee2: {
    name: 'Professor Raymond Cooper',
    jobTitleRelationship: 'Academic Supervisor / Personal Character Reference',
    organisation: 'Lancashire Institute of Care Sciences',
    address: 'Preston University Precinct, PR1 2HE',
    telephone: '01772 889900',
    email: 'rcooper@lancashire.ac.uk',
    mayContact: 'Yes',
  },
  dbsSafety: {
    hasDbs: 'Yes',
    dbsNo: '120938475621',
    registeredUpdateService: 'Yes',
    updateServiceChecked: 'Yes',
    everBarred: 'No',
    barDetails: '',
    hasConvictions: 'No',
    convictionDetails: '',
    subjectToDisciplinary: 'No',
    disciplinaryDetails: '',
    applicantAcknowledged: true,
  },
  healthAdjustments: {
    requireAdjustments: 'No',
    adjustmentDetails: '',
    healthConditions: 'No',
    healthDetails: '',
    otherSupportNeeds: 'No',
    otherNeedsDetails: '',
  },
  checklist: {
    proofOfIdentity: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    rightToWorkEvidence: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    proofOfAddress: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    niEvidence: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    dbsCertificate: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    trainingCertificates: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
    bankDetailsChecked: { received: 'Yes', verifiedBy: 'System Pre-check', date: '2026-06-16' },
  },
  declaration: {
    // Beautiful mock handwritten curve signature encoded in SVG DataURL
    signature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100" viewBox="0 0 300 100"><path d="M 20,60 Q 50,20 70,70 T 110,30 T 160,80 T 210,40 T 260,60" fill="none" stroke="emerald" stroke-width="3" stroke-linecap="round"/></svg>',
    date: '2026-06-16',
    printName: 'SARAH ELIZABETH JENKINS',
  },
  officeUse: {
    receivedDate: '2026-06-16',
    shortlisted: 'Yes',
    interviewDateTime: 'Pending booking',
    interviewedBy: '',
    outcome: '',
    conditionalOfferSent: 'No',
    conditionalOfferDate: '',
    referencesStatus: 'Requested',
    rtwCompleted: 'Yes',
    dbsChecked: 'Yes',
    dbsCheckedDate: '2026-06-16',
    inductionBookedCompleted: 'Booked',
    startDateAgreed: '',
    recruitingManagerSignature: 'H. Rostron',
    recruitingManagerName: 'Hannah Rostron',
    recruitingManagerDate: '2026-06-16',
    decisionNotes: 'Highly promising applicant portfolio. Outstanding references from Jeanette at St Andrews. Move quickly to interview stage.',
  },
};
